import axios from "axios";


const params = new URLSearchParams()
// params.append('grant_type', grant_type)
// params.append('resource', resource)
// params.append('client_id', client_id)
// params.append('client_secret', client_secret)

function getToken() {
    return "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvY2hpcm9uaXRjb20uc2hhcmVwb2ludC5jb21AOWY2YTU3ZmEtZGRlMS00NDAwLWExZjUtOTIzNjRmNDNlZDMxIiwiaXNzIjoiMDAwMDAwMDEtMDAwMC0wMDAwLWMwMDAtMDAwMDAwMDAwMDAwQDlmNmE1N2ZhLWRkZTEtNDQwMC1hMWY1LTkyMzY0ZjQzZWQzMSIsImlhdCI6MTYyNDg5OTQwMCwibmJmIjoxNjI0ODk5NDAwLCJleHAiOjE2MjQ5ODYxMDAsImlkZW50aXR5cHJvdmlkZXIiOiIwMDAwMDAwMS0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDBAOWY2YTU3ZmEtZGRlMS00NDAwLWExZjUtOTIzNjRmNDNlZDMxIiwibmFtZWlkIjoiNDhlMmEzZDgtOGU1My00ODEzLTgwNzItMDk4ZGM4OGY1ZGYzQDlmNmE1N2ZhLWRkZTEtNDQwMC1hMWY1LTkyMzY0ZjQzZWQzMSIsIm9pZCI6IjQzZDVmMzM1LTFkZDQtNDI0MC1hODc2LWRlY2RiNTNhYjNjMCIsInN1YiI6IjQzZDVmMzM1LTFkZDQtNDI0MC1hODc2LWRlY2RiNTNhYjNjMCIsInRydXN0ZWRmb3JkZWxlZ2F0aW9uIjoiZmFsc2UifQ.EOHSB1T2lXnHiyyo1YZDZ9AfYwSjjfTP18d1sVbqhPXvzP1VaA3BusIYBiOw4xZDEdbxB_hbYgmjjG99rA3F5Q9tyMe39HpvI_ebbpH50Ri46WjwDj_BiBJ5sWy6T3-tgAmNFRMTh3DMBOMTektII_4XqugdtwICAV2lByVq6KUURsIhCaSiQ8foAfEQmQcwMBqhuz7lwNJlhXw0iYnU_UqCxLQyclqDEHrSICHR5VoC-QUVoIQzQUDLn8mMW5k46rDNfS_-C3uQ5y_QWJHdE-IvLw8lmksVToj3RMjFiJGJ1WPKg79eoVEUZDodVibGxCUJ3LPltT4tM0xMVfGYxw";
    return axios.post("https://accounts.accesscontrol.windows.net/9f6a57fa-dde1-4400-a1f5-92364f43ed31/tokens/OAuth/2", params, {
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        }
    });
}
export default getToken;